apiVersion: v1
kind: Service
metadata:
  name: postgres-primary
spec:
  ports:
    - port: 5432
      name: postgres
  clusterIP: None # Headless service for stable DNS
  selector:
    app: postgres-primary
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-primary
spec:
  serviceName: postgres-primary
  replicas: 1
  selector:
    matchLabels:
      app: postgres-primary
  template:
    metadata:
      labels:
        app: postgres-primary
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: twitter
        - name: POSTGRES_USER
          value: twitter_user
        - name: POSTGRES_PASSWORD
          value: password
        volumeMounts:
        - name: postgres-primary-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-primary-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
